"""empty message

Revision ID: 0d33c1b769a3
Revises: 7e4daa00127f
Create Date: 2022-05-13 15:32:41.779090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d33c1b769a3'
down_revision = '7e4daa00127f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('custom', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'custom')
    # ### end Alembic commands ###
