"""empty message

Revision ID: 47bcd847dc29
Revises: 
Create Date: 2022-05-12 06:22:38.147296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47bcd847dc29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('kids', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['kids'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'kids')
    # ### end Alembic commands ###
