"""empty message

Revision ID: 5b3021b64cf3
Revises: 0d33c1b769a3
Create Date: 2022-05-13 15:40:05.824123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3021b64cf3'
down_revision = '0d33c1b769a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_id', sa.Column('custom', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_id', 'custom')
    # ### end Alembic commands ###
