"""empty message

Revision ID: 6792f1efffdf
Revises: 5a293aadffa8
Create Date: 2022-05-12 11:57:22.087066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6792f1efffdf'
down_revision = '5a293aadffa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('kid', sa.Boolean(), nullable=True))
    op.drop_column('comments', 'kids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('kids', sa.INTEGER(), nullable=True))
    op.drop_column('comments', 'kid')
    # ### end Alembic commands ###
