"""empty message

Revision ID: 7e4daa00127f
Revises: 6792f1efffdf
Create Date: 2022-05-12 11:59:21.937562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4daa00127f'
down_revision = '6792f1efffdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('replied', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'replied')
    # ### end Alembic commands ###
